title: BG2FOU.github.io
description: "Satellite - jekyll blog theme"
logo_img: "/assets/img/deathstar.png"
profile_img: "/assets/img/BG2FOU.jpg"

# Social Links
email: BG2FOU@outlook.com
github_username: BG2FOU
twitter_username: twitter
bilibili_uid: 354757342
instagram_username: instagram
linkedin_username: linkedin
facebook_username: facebook
qrz_callsign: BG2FOU
 
# Site legal / ICP
beian: 闽ICP备2025114531号
copyright_text: COPYRIGHT ©BG2FOU

# External API
giscus_repo: "BG2FOU/BG2FOU.github.io"
giscus_repoId: "R_kgDOPBoGNQ"
giscus_category: "Q&A"
giscus_categoryId: "DIC_kwDOPBoGNc4C19cU"
goatcounter_code: byanko77
google_analytics:

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /myblog
baseurl:

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy

exclude:
  - docs/

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"

# Markdown newline activator 
kramdown:
  input: GFM
  hard_wrap: true
